platform :ios, '17.5'
use_frameworks!

target 'Cinerama Maps' do
  # Networking
  pod 'Alamofire'
  pod 'SwiftyJSON'

  # Google Maps
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'GooglePlaces'

  # Firebase
  pod 'FirebaseCore'
  pod 'FirebaseMessaging'

  # UI Components
  pod 'Cosmos'
  pod 'SkeletonView'
  pod 'SnapKit'
  pod 'IQKeyboardManagerSwift'
  pod 'DropDown'
  pod 'Parchment'
  pod 'OTPFieldView'
  pod 'NMLocalizedPhoneCountryView'
  pod 'InputMask'

  # Image Loading
  pod 'SDWebImage'
  pod 'SDWebImageWebPCoder'
  pod 'SVGKit'

  # Auth
  pod 'GoogleSignIn'

  # Code Generation
  pod 'R.swift'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.5'
    end
  end
end
